Notepad branched 01
rralys/Notepad pull request #1
Opened 2019-02-19 07:14 UTC by rralys

2019-02-20 21:25 UTC, AnnaS91 requested changes
Отличная работа для начала, но есть, что улучшать

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +import Record.*;
всё таки принято помещать классы не сразу в корень, а создавая для них пакеты. Самая распространенная структура com.bla-bla-bla.src.main - это объясняется во многом влиянием сборщиков. Потом, когда начнем писать тесты в src помимо main появится папка test. Но хотя бы просто src стоит добавить. А если ты будешь все работы делать в одном репозитории, то и пакет с названием домашней работы тоже неплохо было бы завести

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +    private Record[] aNotebook;
а почему не records? в records  будет сразу понятно что отправляется и имена для гетеров и сеттеров будут более говорящими

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +    public void setNotebook(Record[] Notebook) {
переменные в java принято называть со строчной буквы (иначе возникнет путаница с типами)

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +        this.aNotebook = Notebook;
тут есть хороший вопрос - ты же понимаешь, что сейчас присваиваешь ссылку на тот же самый массив, который тебе передали. Соответственно если изменят переданный массив, то изменится и массив рекордов внутри Notepad. Это действительно было задумкой или лучше воспользоваться копированием?

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +        Record newNotebook [len + 1];
увеличивая длину массива каждый раз при добавлении записи на 1, ты каждый раз будешь копировать предыдущие записи. Представь, что юзер закинул 1000 записей. Чтобы добавить 1001-ю, тебе понадобится скопировать 1000 элементов, и при этом ещё и выделить в памяти 2001 ячейку под элементы, что ударит не только по perfomanc-у, но и по расходу памяти. Так что логичнее делать путем, про который я рассказывала на лекции - ты достигаешь определенной границы и потом расширяешь массив, увеличивая его длину на определенный коэффициент

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +public class Notebook {
довольно опасное отсутствие конструктора. В программе можно создать твой класс, вызвать, например, метод addRecord и схлопотать по лбу, потому что массив не проинициализирован, а только объявлен

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +
а где ты возвращаешь -1 в случае неудачи?

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +        int i;
лучше объявлять прямо в цикле

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +    public Notebook removeRecord(String phoneNumber) {
возможно стоило бы возвращать из этого метода удаленный Record (но не обязательно)

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +        Record newNotebook [len - 1];
аналогичная проблема, как описанная выше для расширения массива

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +        textRecord = textRecord.concat(curRecord.getFirstName());
1. здесь можно было бы записать просто через + в одно действие. А ещё лучше воспользоваться StringBuilder-ом или использовать метод String.format, задав для него паттер вида "%s %s %s %s %s
2. Эта часть метода полностью относится к Record-у, поэтому было бы логично разместить её именно в классе рекорд (возможно просто переопределив у него метод toString)

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +        for (int i = 0; i < len; i++) {
какой цикл лучше отвечает твоей цели?

2019-02-20 21:25 UTC, AnnaS91 commented on Record/record.java
> +    public void Record(String first, String last, String phNumber) {
можно было бы создать несколько конструкторов и использовать вызовы одного из другого, для того чтобы обхватить как можно больше вариаций создания

2019-02-20 21:25 UTC, AnnaS91 commented on Notebook/notebook.java
> +        Record curRecord = this.aNotebook[recIndex];
а что произойдет, если я передам отрицательный индекс или индекс, больший длинны массива?

2019-02-22 19:14 UTC, rralys commented on Notebook/notebook.java
> +import Record.*;
@AnnaS91, я посмотрел какие есть опции по созданию различных элементов в моей версии Идеи (это 2018.1.7) в меню new. Там есть папка и файл. Я не вижу там опций создания пакетов и классов. Это нужно делать какими-то шорткатами?

2019-02-22 19:42 UTC, rralys commented on Notebook/notebook.java
> +        this.aNotebook = Notebook;
На момент написания я не до конца осознал, что присваивается ссылка на объект, а не сам объект... Поэтому да, копирование.

2019-02-22 20:49 UTC, rralys commented on Notebook/notebook.java
> +        textRecord = textRecord.concat(curRecord.getFirstName());
Перенёс логику в класс Record, где (вроде бы) переопределил метод toString().

2019-02-22 20:49 UTC, rralys commented on Notebook/notebook.java
> +        for (int i = 0; i < len; i++) {
Конечно, for each. Переделал этот кусок.

2019-02-22 20:50 UTC, rralys commented on Record/record.java
> +    public void Record(String first, String last, String phNumber) {
Я пока не очень понимаю, как это внятно сделать. Может обсудим в понедельник?

2019-02-22 20:51 UTC, rralys commented on Notebook/notebook.java
> +        Record curRecord = this.aNotebook[recIndex];
Переработал цикл for, чтобы избежать лишних проверок.

2019-02-22 20:51 UTC, rralys commented on Notebook/notebook.java
> +        Record newNotebook [len + 1];
Переработал оба метода: как добавление, так и удаление.

2019-02-22 20:52 UTC, rralys commented on Notebook/notebook.java
> +    private Record[] aNotebook;
Одна запись всё же Record, поэтому и класс так назвал.

2019-02-22 20:52 UTC, rralys commented on Notebook/notebook.java
> +    public void setNotebook(Record[] Notebook) {
Переименовал.

2019-02-22 20:53 UTC, rralys commented on Notebook/notebook.java
> +import Record.*;
Разобрался, вроде, с созданием пакетов и классов.

2019-03-06 14:56 UTC, AnnaS91 requested changes

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +package Notepad.Notebook;
все пакеты (папки) именуются с маленькой буквы. Классы, enums, интерфейсы - с большой

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +        Record[] aNotebook = new Record[100];
тут есть проблема: раз ты заново объявляешь aNotebook, ты получается не работаешь напрямую с полем класса, а создаешь ещё один массив

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +        this.aNotebook = notebook;
если у тебя есть конструктор, зачем тебе доп метод для setNotebook?

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +            newLen = (int) ((int) len * 1.5);
зачем так много приведений типов?

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +        int newLen;
можно сразу же проинициализировать

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +        int i;
используется только в цикле, логичнее объявить там же

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +            if (curPhoneNumber.equals(phoneNumber)) {
если ты что-то используешь всего один раз, не обязательно записывать это в переменную, можно сравнивать напрямую выражения

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +        if (lastRecord == java.lang.Math.floorDiv(len, 2)) {
а почему не импортишь Math?

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +        int recIndex = this.findRecord(phoneNumber);
this можно опустить

2019-03-06 14:56 UTC, AnnaS91 commented on Notebook/Notebook.java
> +        for (Record curRec : aNotebook) {
а у тебя нормально работает без проверки на null?

2019-03-06 14:56 UTC, AnnaS91 commented on Record/Record.java
> +    public Record populateRecord() {
1) метод работающий со сканером лучше разместить в общем классе и создавать рекорд с помощью конструктора, потому как рекорд же можно создавать и читая из файла, и получая из сети и задавая напрямую
2) метод работает не корректно: ты объявляешь новые переменные вместо того, чтобы использовать поля класса. Поэтому в this у тебя ничего не поменяется

2019-03-06 14:56 UTC, AnnaS91 commented on Record/Record.java
> +        res = firstName + " " + lastName + " " + phoneNumber + " " + email + " " + address;
1) можно объединить инициализацию и объявление
2) операция конкатенации довольно дорогая, лучше использовать String.format или StringBuilder

2019-03-06 14:56 UTC, AnnaS91 commented on Record/Record.java
> +    public String toString() {
стоит добавить аннотацию

2019-03-06 14:56 UTC, AnnaS91 commented on Record/Record.java
> +    public void showRecord(){
в целом этот метод не нужен, можно просто запрашивать toString

2019-03-06 17:32 UTC, rralys commented on Notebook/Notebook.java
> +        this.aNotebook = notebook;
Я подумал, что нужно дать возможность передать готовый ноутбук.

2019-03-06 17:33 UTC, rralys commented on Notebook/Notebook.java
> +            newLen = (int) ((int) len * 1.5);
Убрал лишнее приведение.

2019-03-06 17:33 UTC, rralys commented on Notebook/Notebook.java
> +        int newLen;
Инициализировал.

2019-03-06 17:33 UTC, rralys commented on Notebook/Notebook.java
> +package Notepad.Notebook;
Поменял структуру проекта, теперь нет пакетов.

2019-03-06 17:34 UTC, rralys commented on Notebook/Notebook.java
> +        Record[] aNotebook = new Record[100];
Убрал объявление.

2019-03-06 17:35 UTC, rralys commented on Notebook/Notebook.java
> +        int i;
Объявил в цикле.

2019-03-06 17:36 UTC, rralys commented on Notebook/Notebook.java
> +            if (curPhoneNumber.equals(phoneNumber)) {
Убрал лишнее объявление.

2019-03-06 17:37 UTC, rralys commented on Notebook/Notebook.java
> +        if (lastRecord == java.lang.Math.floorDiv(len, 2)) {
Проимпортировал.

2019-03-06 17:38 UTC, rralys commented on Notebook/Notebook.java
> +        int recIndex = this.findRecord(phoneNumber);
Убрал.

2019-03-06 17:38 UTC, rralys commented on Notebook/Notebook.java
> +        for (Record curRec : aNotebook) {
Добавил проверку.

2019-03-06 17:40 UTC, rralys commented on Record/Record.java
> +    public Record populateRecord() {
Поправил обращение к полям.

Не очень понял на счёт сканера в общем классе.

2019-03-06 17:48 UTC, rralys commented on Record/Record.java
> +        res = firstName + " " + lastName + " " + phoneNumber + " " + email + " " + address;
Я решил, что лучше сразу возвращать значение, возвращаемое методом format.

2019-03-06 17:50 UTC, rralys commented on Record/Record.java
> +    public void showRecord(){
Вызываю сразу toString().

2019-03-16 10:56 UTC, rralys commented on Record/Record.java
> +    public Record populateRecord() {
Убрал обращение к сканеру.

2019-03-23 13:54 UTC, AnnaS91 requested changes

2019-03-23 13:54 UTC, AnnaS91 commented on src/Record.java
> +import java.util.Scanner;
ненужный импорт, удаляй

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +        aNotebook = new Record[100];
100 лучше вынести в константу класса

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +        this.aNotebook = notebook;
1) лучше всё-таки скопировать содержание массива, а не присваивать на него ссылку. Иначе если у тебя в программе модифицируют массив, он изменится и внутри класса
2) почему при таком способе задания не меняешь lastRecord?

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +        Record[] newNotebook = new Record[newLen];
получается, что даже не изменив длинну ты запускаешь операцию копирования и тратишь на это время и память, что не есть хорошо. Луше вынести код расширения в отдельный метод и вызывать его только при необходимости

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +                res = i;
здесь обязательно нужно добавить break; либо сразу return i - и тогда тебе даже не понадобится заводить переменную res. В твоём же случае, даже если первая запись совпадает, ты всё равно проходишь по всему массиву

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +    public Notebook removeRecord(String phoneNumber) {
может стоило бы возвращать true в случае если удаление прошло и false для отрицательных кейсов

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +            newLen = (int) (len * 0.75);
0.75 тоже лучше вынести в константу

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +                System.out.println(curRec.toString());
в println можно передавать объект, и для него уже внутри будет вызван метод toString

2019-03-23 13:54 UTC, AnnaS91 commented on src/Notebook.java
> +    public Record[] getNotebook(){
а тебе точно нужен этот метод, он довольно опасен, потому что отдавая массив наружу, ты разрешаешь пользователю модифицировать его как ему заблогорассудится, что может привести к некорректной работе методов самого Notebook

2019-03-23 13:54 UTC, AnnaS91 commented on src/NotebookTest.java
> +    public void createRecord() {
а почему создание рекорда и блокнота разнесены в разные методы? было бы логично объединить их

2019-03-23 13:54 UTC, AnnaS91 commented on src/NotebookTest.java
> +    public void testAdd(){
лучше называя тесты всё-таки следовать парадигме BDD, например, addRecordShouldChangeCurrentIndex

2019-03-25 09:32 UTC, rralys commented on src/Record.java
> +import java.util.Scanner;
Удалено.

2019-03-25 09:32 UTC, rralys commented on src/Notebook.java
> +        aNotebook = new Record[100];
Готово.

2019-03-25 09:34 UTC, rralys commented on src/Notebook.java
> +        this.aNotebook = notebook;
1. Поменял на копирование.
2. Меняю lastRecord на значение от нового массива. Написал отдельный метод для нахождения (getLastRecordIndex).

2019-03-25 09:45 UTC, rralys commented on src/Notebook.java
> +        Record[] newNotebook = new Record[newLen];
Наконец-то понял твою логику :-). Поменял метод.

2019-03-25 09:45 UTC, rralys commented on src/Notebook.java
> +                res = i;
Вызываю брейк и в том случае, если найдено, и в том случае, если попался null, т.к. это означает, что больше актуальных записей нет.

2019-03-25 09:46 UTC, rralys commented on src/Notebook.java
> +            newLen = (int) (len * 0.75);
Готово.

2019-03-25 09:46 UTC, rralys commented on src/Notebook.java
> +                System.out.println(curRec.toString());
Поменял, спасибо :-).

2019-03-25 09:47 UTC, rralys commented on src/Notebook.java
> +    public Record[] getNotebook(){
Поменял логику, теперь вызываю метод getNotebookLen в тестах, чтобы понять длину массива.

2019-03-25 09:47 UTC, rralys commented on src/NotebookTest.java
> +    public void createRecord() {
Объединено.

2019-03-25 09:48 UTC, rralys commented on src/NotebookTest.java
> +    public void testAdd(){
Поменял названия на что-то более говорящее.

2019-03-25 16:44 UTC, AnnaS91 approved these changes

2019-03-25 18:47 UTC, merged